name: AI Chat Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Run logger tests
      run: |
        python utils/logger.py
    
    - name: Run basic integration tests
      run: |
        python -c "
        from utils.logger import get_logger
        from utils.driver_manager import WebDriverManager
        from utils.element_finder import ElementFinder, FindStrategy
        
        logger = get_logger('github_actions_test')
        logger.info('🚀 GitHub Actions test starting')
        
        # Test logger functionality
        with logger.log_performance('test_operation'):
            import time
            time.sleep(0.1)
        
        logger.info('✅ All modules imported successfully')
        logger.info('✅ Performance logging working')
        logger.log_performance_summary()
        print('🎉 GitHub Actions test completed successfully')
        "
    
    - name: Validate configuration
      run: |
        python -c "
        import json
        with open('config/config.json', 'r') as f:
            config = json.load(f)
        print('✅ Configuration file is valid JSON')
        print(f'Services configured: {list(config.keys())}')
        "